In [44]:
import numpy as np

# Input dataset

| | $x_1$ | $x_2$ | $x_3$ |$y$|
|-- | --- | --- | --- |--|
|Sample 1| 0 | 0 |1| 0 |
|Sample 2| 0 | 1 |1| 1 |
|Sample 3| 1 | 1 |1| 1 |
|Sample 4| 1 | 1 |1| 0 |

### Here, $X$ is the input data matrix, where $x_1, x_2, x_3$ are input features (a.k.a., variables, attributes) of the 4 samples.
### $y$ is the output vector, containing target label of each of the 4 samples.

## Goal: Given two new samples:
| | $x_1$ | $x_2$ | $x_3$ |$y$|
|-- | --- | --- | --- |--|
|Sample 5| 1 | 0 |0| ? |
|Sample 6| 0 | 0 |0| ? |
## We need to predict their target class labels.

In [37]:
X = np.array( [[0,0,1], [0, 1, 1], [1, 0, 1], [1,1,1]])


In [38]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [39]:
y = np.array( [ [0], [1], [1], [0]])

In [40]:
y

array([[0],
       [1],
       [1],
       [0]])

# Constructing & initializing the network

In [41]:
SynapseMatrix1 = np.random.random((3,4))
SynapseMatrix2 = np.random.random((4,1))

In [42]:
SynapseMatrix1

array([[0.87343119, 0.85825995, 0.53739446, 0.00681952],
       [0.72593786, 0.45707645, 0.29857254, 0.81004184],
       [0.34786019, 0.05219962, 0.76017912, 0.70161249]])

In [43]:
SynapseMatrix2

array([[0.98377904],
       [0.13987186],
       [0.42502164],
       [0.22341134]])

# Training step

In [28]:
def sigmoidActivation(x):
    return 1 / (1 + np.exp(-x))
    # return expit(x)     #More practical solution. However, you need to import it: from scipy.special import expit

In [29]:
def derivative_of_sigmoid(x):
    return x*(1-x)

In [30]:
for i in np.arange(100000):
    layer0 = X
    layer1 = sigmoidActivation(np.dot(layer0, SynapseMatrix1))
    layer2 = sigmoidActivation(np.dot(layer1, SynapseMatrix2))
    
    layer2_error = y - layer2
    
    if (i% 1000)==0:
        print ("Error: "+str(np.mean(np.abs(layer2_error))))
    
    layer2_delta = layer2_error*derivative_of_sigmoid(layer2)
    
    
    layer1_error = layer2_delta.dot(SynapseMatrix2.T)
    
    layer1_delta = layer1_error*derivative_of_sigmoid(layer1)
    
    #Update weights
    SynapseMatrix2 = SynapseMatrix2 + layer1.T.dot(layer2_delta)
    SynapseMatrix1 = SynapseMatrix1 + layer0.T.dot(layer1_delta)

#output after the training
print("Output after training:")
print(layer2)

Error: 0.49709211349468047
Error: 0.06296426951908099
Error: 0.0354222132843419
Error: 0.026825821274925943
Error: 0.02233430842704525
Error: 0.01948519428985094
Error: 0.01747975646199209
Error: 0.015973063439082863
Error: 0.014789258119871095
Error: 0.013828274136270951
Error: 0.013028521864787791
Error: 0.012349787236456876
Error: 0.011764573605359582
Error: 0.0112533702984512
Error: 0.010801905426620795
Error: 0.010399470102510345
Error: 0.010037853418818644
Error: 0.009710641724627853
Error: 0.009412743703277422
Error: 0.009140060106600014
Error: 0.00888924885935793
Error: 0.008657554643826382
Error: 0.008442683062128548
Error: 0.008242706235298134
Error: 0.008055990970479817
Error: 0.007881143392190438
Error: 0.007716965760972702
Error: 0.007562422434336797
Error: 0.0074166127695998825
Error: 0.007278749357018609
Error: 0.007148140388093507
Error: 0.007024175262565236
Error: 0.006906312754464883
Error: 0.0067940712168717155
Error: 0.006687020423318117
Error: 0.006584774732509629


In [31]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
# Sample 5
layer0 = np.array( [[1,0,0]])
layer1 = sigmoidActivation(np.dot(layer0, SynapseMatrix1))
layer2 = sigmoidActivation(np.dot(layer1, SynapseMatrix2))

In [33]:
layer2

array([[0.9950113]])

In [34]:
# Sample 6
layer0 = np.array( [[0,0,0]])
layer1 = sigmoidActivation(np.dot(layer0, SynapseMatrix1))
layer2 = sigmoidActivation(np.dot(layer1, SynapseMatrix2))

In [35]:
layer2

array([[0.06083391]])